//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class newDatabaseEntities : DbContext
    {
        public newDatabaseEntities()
            : base("name=newDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Bundle> Bundle { get; set; }
        public virtual DbSet<POrder> POrder { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<POrderCustomer> POrderCustomer { get; set; }
    }
}
